# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/mt6768-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter a32,$(TARGET_DEVICE)),)

endif
